version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      # installing deps 
      - run:
          name: Installing packages
          command: yarn
      # building for production
      - run:
          name: Building Frontend
          command: yarn build
      # installing aws cli
      - aws-cli/install
      - run:
          name: Deploy Frontend
          # deploying
          command: |-
            cat ~/.aws/*
            aws s3 cp --recursive --acl public-read ./www $S3_FRONTEND_BUCKET
  api:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Installing packages
          command: yarn
      - run:
          name: Build and Archive The Server
          command: |-
            yarn build
      - aws-cli/install
      # installing eb cli
      - aws-eb/setup
      - run:
          name: Deploying API
          command: |-
            yarn deploy
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - api
