version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Installing packages
          command: yarn
      - run:
          name: Testing Frontend
          command: yarn test
      - run:
          name: Building Frontend
          command: yarn build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www $S3_FRONTEND_BUCKET
  api:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Installing packages
          command: yarn
      - run:
          name: Build and Archive The Server
          command: |-
            yarn build
      - aws-cli/install
      - run:
          name: Deploying API
          command: |-
            eb create $EB_ENV
            eb use $EB_ENV
            eb deploy
            eb status
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - api
